### ISSUE TITLE
[BE] refactor: SaveDataDto에서 saveUuid, uuid를 삭제한다.

### ISSUE THREAD

**Issue by HyoungUkJo** [jungle-6-3/code-sync-be#143]
## 리팩터링 내용
ConversationDatas엔티티 에서 uuid를 삭제한다.
SaveDataDto에서 saveUuid, uuid를 삭제한다.
saveUuid는 conversationData의 서비스에서 할당한다.

<br/>

**Comment by pig19980** [comment]
room service에서 conversation로 보낼 때 사용하는 DTO, conversation에서 conversation data로 보낼 때 사용하는 DTO, DB에 저장할 때 사용하는 DTO 모두 구별해서 해주세요
