### ISSUE TITLE
[BE] feat: Auth에서 token을 payload로 decode해주는 service 추가

### ISSUE THREAD

**Issue by pig19980** [jungle-6-3/code-sync-be#20]
## 구현 기능
cookie에서 가져온 token이 주어지면, JwtPayloadDto로 감싸서 decode한 결과를 return해주는 service 구현

<br/>

## 작업 내용

<br/>

## 주의사항
1. AuthService에 구현한다.
2. AuthModule에서는 AuthService를 export한다.

**Comment by HyoungUkJo** [comment]
이 수술 제가 집도하겠습니다.
