### ISSUE TITLE
[BE] feat: make Global filter for unexpected error

### ISSUE THREAD

**Issue by HyoungUkJo** [jungle-6-3/code-sync-be#28]
## 구현 기능
각 도메인에서 처리하지 못한 예기치 못한 에러를 처리하는 글로벌 필터를 구현한다.
<br/>

## 작업 내용
1차적으로 500번대 에러 처리하는 로직을 구현 예정입니다.

<br/>

**Comment by pig19980** [comment]
#45 로 통합
