### ISSUE TITLE
[BE] feat: file upload to AWS S3

### ISSUE THREAD

**Issue by HyoungUkJo** [jungle-6-3/code-sync-be#42]
## 구현 기능
S3에 접속해서 파일을 업로드한다.
<br/>

## 작업 내용
s3접속용 .env 설정
테스트용 controller 작성
실제 데이터베이스에 업로드 할 service 구현
<br/>

## 주의사항
검증이 완료되면 controller 삭재

**Comment by pig19980** [comment]
됨
